In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
#dataset=dataset.drop('',axis=1)
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
dep=dataset[['classification_yes']]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
from sklearn.model_selection import GridSearchCV
param_grid={'criterion': ['gini','entropy','log_loss'],
           'splitter': ['best', 'random'],
            'max_features':['auto','sqrt','log2']
           }
grid=GridSearchCV(DecisionTreeClassifier(),param_grid=param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')

grid.fit(x_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\Manikandan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Manikandan\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Manikandan\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\Manikandan\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Manikandan\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [0.97353957 0.96625862 0.95525647 0.973735   0.95103691 0.9584677
 0.96281588 0.98131699 0.93242586 0.95134958 0.95114327 0.96265757
        nan        nan        nan        nan        nan        nan]
  category=UserWarning,

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [14]:
#print best parameter after tunning
gre=grid.cv_results_

#print(gre)
grid_prediction=grid.predict(x_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)

In [15]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_prediction)

In [16]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_prediction,average='weighted')
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'criterion': 'entropy', 'max_features': 'auto', 'splitter': 'random'}: 0.9775556904684072

In [17]:
print("confusion matrix :\n",cm)

confusion matrix :
 [[51  0]
 [ 3 79]]

In [18]:
print("classification_report:\n",clf_report)

classification_report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9817073170731707

In [20]:
table=pd.DataFrame.from_dict(gre)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006471,0.001178,0.002002,0.000002,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.963284,0.942166,0.981217,0.981031,1.000000,0.973540,0.019518,3
1,0.006338,0.002344,0.001840,0.000429,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.963284,0.943699,1.000000,0.981217,0.943093,0.966259,0.021985,4
2,0.004603,0.000959,0.002905,0.003074,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.963284,0.943699,0.907035,1.000000,0.962264,0.955256,0.030247,8
3,0.005809,0.001342,0.001611,0.000499,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.962963,0.981014,0.962264,0.981217,0.981217,0.973735,0.009084,2
4,0.005030,0.000938,0.001621,0.000508,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.945100,0.923510,0.981217,0.943093,0.962264,0.951037,0.019457,11
5,0.004087,0.000086,0.001227,0.000444,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.981569,0.943041,0.962573,0.905155,1.000000,0.958468,0.032728,7
6,0.003798,0.000351,0.001402,0.000488,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.926978,0.962264,0.962573,0.962264,1.000000,0.962816,0.023098,5
7,0.002322,0.000603,0.001052,0.000085,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.944135,0.981233,0.981217,1.000000,1.000000,0.981317,0.020399,1
8,0.002246,0.000383,0.000804,0.000402,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.908877,0.923510,0.925146,0.942332,0.962264,0.932426,0.018306,12
9,0.001813,0.000407,0.000803,0.000401,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.908501,0.962264,1.000000,0.942332,0.943651,0.951350,0.029875,9
10,0.002818,0.000549,0.000808,0.000404,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.981569,0.961755,0.907035,0.943093,0.962264,0.951143,0.025189,10
11,0.003021,0.000031,0.000635,0.000523,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.945100,0.943041,0.962573,0.962573,1.000000,0.962658,0.020433,6
12,0.002819,0.000680,0.000000,0.000000,log_loss,auto,best,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.003094,0.000544,0.000000,0.000000,log_loss,auto,random,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
14,0.002735,0.000594,0.000000,0.000000,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
15,0.002100,0.000149,0.000000,0.000000,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
16,0.002455,0.000528,0.000000,0.000000,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
17,0.001830,0.000595,0.000000,0.000000,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,18